[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "versioneer-518"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | docs
)/
'''

[tool.towncrier]
name = "PyMojang"
directory = "changes"
package = "mojang"
filename = "CHANGELOG.rst"
issue_format = "`#{issue} <https://github.com/Lucino772/pymojang/issues/{issue}>`_"