# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Testing
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Install uv and setup Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.14"
        python-version: ${{ matrix.python-version }}
    # - name: Lint
    #   run: |
    #     hatch fmt --check
    - name: Test
      run: |
        uv run --dev pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment: Deployment
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          pipx run build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
