name: pre-commit

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: pre-commit/action@v2.0.3